### PR TITLE
Fix the bug where desc [INDEX] doesn't clear description

### LINKED ISSUE #105: Desc not deleting a description when description is omitted

### PR DESCRIPTION
**Pull request by dingZvel**
fixes #105

### CODE REVIEW

**Review by TobyCyan — APPROVED** [review]
LGTM!

**Review by nlqhung130403 — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -107,7 +107,7 @@ private static Client createEditedClient(Client clientToEdit, EditClientDescript
         Optional<ProductPreference> updatedProductPreference =
                 editClientDescriptor.getProductPreference().or(() -> clientToEdit.getProductPreference());
         Optional<Description> updatedDescription =
-                editClientDescriptor.getDescription().or(() -> clientToEdit.getDescription());
+                editClientDescriptor.getDescription();
```
Comment (nlqhung130403) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:110]: this will always delete the description of the new client
